name: Update Solved Problems Count

on:
  push:
    branches:
      - master

jobs:
  update-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Count Solved problems
        id: count_problems
        run: |
          python -c "
          import os

          def count_problems(directory):
              count = 0
              for root, _, files in os.walk(directory):
                  for file in files:
                      if file.endswith('.py') or file.endswith('.java'):
                          count += 1
              return count

          count = count_problems('.')
          with open('README.md', 'r') as file:
              lines = file.readlines()
          lines[-1] = f'Total Problems Solved: {count}\\n'
          with open('README.md', 'w') as file:
              file.writelines(lines)
          "

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update solved problems count"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
