name: Update README with Commit Count

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Count commits
      id: count-commits
      run: echo "::set-output name=count::$(git rev-list --count HEAD)"

    - name: Update README
      run: |
        COMMIT_COUNT=$(git rev-list --count HEAD)
        sed -i "s/Problems Solved: [0-9]*/Problems Solved: $COMMIT_COUNT/" README.md
        cat README.md  # Display the updated README for debugging

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update problem count in README [skip ci]"
        git push
